In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_csv('/content/car_age_price.csv')

In [24]:
df.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [25]:
df.tail()

     Year   Price
107  2016  375000
108  2014  300000
109  2015  425000
110  2016  420000
111  2015  425000

In [26]:
df.shape

(112, 2)

In [27]:

# define feature and target

X = df[['Year']]  # feature
y = df[['Price']]  # target

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size= 0.2, random_state = 42
)

In [29]:
# Linear Regression Model
from sklearn.linear_model import LinearRegression, Lasso

linear_model = LinearRegression()
linear_model.fit(X_train,y_train)
linear_preds = linear_model.predict(X_test)

In [30]:
# Lasso Regression Model

lasso_model = Lasso(alpha = 1000)
lasso_model.fit(X_train, y_train)
lasso_preds = lasso_model.predict(X_test)

In [31]:
from sklearn.metrics import mean_squared_error,r2_score

In [32]:
lin_reg_rmse = mean_squared_error(y_test,linear_preds)
lasso_reg_rmse = mean_squared_error(y_test,lasso_preds)

lin_reg_r2 = r2_score(y_test, linear_preds)
lasso_reg_r2 = r2_score(y_test,lasso_preds)

In [33]:
print("\n Linear Regression RMSE =", lin_reg_rmse )
print("\n Linear Regression R2 =", lin_reg_r2 )
print("\n Lasso Regression RMSE =", lasso_reg_rmse )
print("\n Lasso Regression R2 =", lasso_reg_r2 )

 Linear Regression RMSE = 4326906256.829671

 Linear Regression R2 = 0.36759313425902185

 Lasso Regression RMSE = 4281012112.630084

 Lasso Regression R2 = 0.37430087650402977

In [34]:
year_2022 = np.array([[2022]])
price_lin_2022 = linear_model.predict(year_2022)[0]
price_lasso_2022 = lasso_model.predict(year_2022)[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(

In [35]:
print("\nPredicted Price for 2022 Model:")
print("Linear Regression:", price_lin_2022)
print("Lasso Regression:", price_lasso_2022)

Predicted Price for 2022 Model:
Linear Regression: [743601.61594504]
Lasso Regression: 741359.9423397332